name: Windows Testing

on: [push]

jobs:
  build:
    name: Windows Test
    runs-on: windows-latest
    steps:
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - name: Enabing Networking Firewall
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Setting up RDP TCP UserAuthentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Creating Local User
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $Env:WINDOWS_USER_PASSWORD -Force)
      env:
        WINDOWS_USER_PASSWORD: RealKoolisw@!
