name: Windows 10 CRD

on: 
  workflow_dispatch:
   inputs:
      crdauthcode:
        description: 'Enter ChromeRemoteDesktop Headless code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true

jobs:
  build:
    name: Windows 10 Build
    runs-on: windows-latest
    
    steps:
    - name: Creating Local User
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $Env:WINDOWS_USER_PASSWORD -Force)
      env:
        WINDOWS_USER_PASSWORD: ${{ secrets.WINDOWS_USER_PASSWORD }}
    - name: Setting Up Chrome Remote Desktop
      run: ./win10-chrome-remote/setup.ps1
    - name: Connecting to Chrome Remote Desktop
      run: ${{ github.event.inputs.crdauthcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Looping the process
      run: ./win10-chrome-remote/loop.ps1
