name: Windows Server 2019

on: 
  workflow_dispatch:

jobs:
  build:
    name: Windows 10 Build
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
    - name: Download
      run: |
       Invoke-WebRequest https://github.com/RealKoolisw/FREE-RDP-VirtualMachine/releases/download/ngrok/ngrok.exe -OutFile ngrok.exe
       Invoke-WebRequest https://github.com/RealKoolisw/VirtualMachine-GithubAction/blob/main/resources/nssm.exe?raw=true -OutFile nssm.exe
       Invoke-WebRequest https://raw.githubusercontent.com/RealKoolisw/FREE-RDP-VirtualMachine/main/resources/ngrok-user.bat -OutFile ngrok-user.bat
       Invoke-WebRequest https://raw.githubusercontent.com/mrX04/Windows2019RDP-US/main/ngrok-start.bat -OutFile ngrok-start.bat
       Invoke-WebRequest https://raw.githubusercontent.com/RealKoolisw/FREE-RDP-VirtualMachine/main/resources/ngrok-loop.bat -OutFile ngrok-loop.bat
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Auth
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Installing Ngrok Process as a Windows Core Services
      run: start ngrok-start.bat
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - name: Enabing Networking Firewall
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Setting up RDP TCP UserAuthentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: sc start ngrok
    - name: Connecting Process
      run: cmd /c ngrok-user.bat
      env:
        WINDOWS_USER_PASSWORD: ${{ secrets.WINDOWS_USER_PASSWORD }}
    - name: Looping Process
      run: cmd /c ngrok-loop.bat
